services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=music_events'
      - 'POSTGRES_PASSWORD=geheim123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
